# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BankAccount.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BankAccount.proto',
  package='Chronos.BankAccount',
  serialized_pb=_b('\n\x11\x42\x61nkAccount.proto\x12\x13\x43hronos.BankAccount\"?\n\x0b\x42\x61nkAccount\x12\r\n\x05owner\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\x05\x12\x10\n\x08isClosed\x18\x03 \x01(\x08\",\n\x0b\x43reateEvent\x12\r\n\x05owner\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\"\x1e\n\x0c\x44\x65positEvent\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x05\"\x1f\n\rWithdrawEvent\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x05\"\x0c\n\nCloseEvent')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BANKACCOUNT = _descriptor.Descriptor(
  name='BankAccount',
  full_name='Chronos.BankAccount.BankAccount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='owner', full_name='Chronos.BankAccount.BankAccount.owner', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='balance', full_name='Chronos.BankAccount.BankAccount.balance', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isClosed', full_name='Chronos.BankAccount.BankAccount.isClosed', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=105,
)


_CREATEEVENT = _descriptor.Descriptor(
  name='CreateEvent',
  full_name='Chronos.BankAccount.CreateEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='owner', full_name='Chronos.BankAccount.CreateEvent.owner', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amount', full_name='Chronos.BankAccount.CreateEvent.amount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=151,
)


_DEPOSITEVENT = _descriptor.Descriptor(
  name='DepositEvent',
  full_name='Chronos.BankAccount.DepositEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='amount', full_name='Chronos.BankAccount.DepositEvent.amount', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=183,
)


_WITHDRAWEVENT = _descriptor.Descriptor(
  name='WithdrawEvent',
  full_name='Chronos.BankAccount.WithdrawEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='amount', full_name='Chronos.BankAccount.WithdrawEvent.amount', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=216,
)


_CLOSEEVENT = _descriptor.Descriptor(
  name='CloseEvent',
  full_name='Chronos.BankAccount.CloseEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=230,
)

DESCRIPTOR.message_types_by_name['BankAccount'] = _BANKACCOUNT
DESCRIPTOR.message_types_by_name['CreateEvent'] = _CREATEEVENT
DESCRIPTOR.message_types_by_name['DepositEvent'] = _DEPOSITEVENT
DESCRIPTOR.message_types_by_name['WithdrawEvent'] = _WITHDRAWEVENT
DESCRIPTOR.message_types_by_name['CloseEvent'] = _CLOSEEVENT

BankAccount = _reflection.GeneratedProtocolMessageType('BankAccount', (_message.Message,), dict(
  DESCRIPTOR = _BANKACCOUNT,
  __module__ = 'BankAccount_pb2'
  # @@protoc_insertion_point(class_scope:Chronos.BankAccount.BankAccount)
  ))
_sym_db.RegisterMessage(BankAccount)

CreateEvent = _reflection.GeneratedProtocolMessageType('CreateEvent', (_message.Message,), dict(
  DESCRIPTOR = _CREATEEVENT,
  __module__ = 'BankAccount_pb2'
  # @@protoc_insertion_point(class_scope:Chronos.BankAccount.CreateEvent)
  ))
_sym_db.RegisterMessage(CreateEvent)

DepositEvent = _reflection.GeneratedProtocolMessageType('DepositEvent', (_message.Message,), dict(
  DESCRIPTOR = _DEPOSITEVENT,
  __module__ = 'BankAccount_pb2'
  # @@protoc_insertion_point(class_scope:Chronos.BankAccount.DepositEvent)
  ))
_sym_db.RegisterMessage(DepositEvent)

WithdrawEvent = _reflection.GeneratedProtocolMessageType('WithdrawEvent', (_message.Message,), dict(
  DESCRIPTOR = _WITHDRAWEVENT,
  __module__ = 'BankAccount_pb2'
  # @@protoc_insertion_point(class_scope:Chronos.BankAccount.WithdrawEvent)
  ))
_sym_db.RegisterMessage(WithdrawEvent)

CloseEvent = _reflection.GeneratedProtocolMessageType('CloseEvent', (_message.Message,), dict(
  DESCRIPTOR = _CLOSEEVENT,
  __module__ = 'BankAccount_pb2'
  # @@protoc_insertion_point(class_scope:Chronos.BankAccount.CloseEvent)
  ))
_sym_db.RegisterMessage(CloseEvent)


# @@protoc_insertion_point(module_scope)
